version: '3'
services:
  web:
    build: .
    volumes:
      - ./Apprunner:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=/app/python/app.py
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase