# Use an official Python runtime as a base image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Run a simple Python HTTP server to serve the static files
CMD ["python", "-m", "http.server", "8000"]